apiVersion: v1
kind: Service
metadata:
  name: task-frontend
  namespace: prod
spec:
  selector:
    app: task-frontend
  type: NodePort
  ports:
  - name: task-frontend
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30001
