apiVersion: v1
kind: Service
metadata:
  name: task-auth
  namespace: prod
spec:
  selector:
    app: task-auth
  type: ClusterIP
  ports:
  - name: task-auth
    protocol: TCP
    port: 8081
    targetPort: 8081
