apiVersion: v1
data:
  PORT: ODA4MQ==
kind: Secret
metadata:
  name: task-auth
  namespace: prod
---
apiVersion: v1
data:
  PORT: ODA4Mg==
kind: Secret
metadata:
  name: task-by-who
  namespace: prod
---
apiVersion: v1
data:
  PORT: ODA4Mw==
kind: Secret
metadata:
  name: task-category
  namespace: prod
---
apiVersion: v1
data:
  PORT: ODA4NA==
kind: Secret
metadata:
  name: task-entry
  namespace: prod
---
apiVersion: v1
data:
  AUTH_URL: aHR0cDovL2lzdGlvLWluZ3Jlc3NnYXRld2F5LmlzdGlvLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbA==
  BY_WHO_URL: aHR0cDovL2lzdGlvLWluZ3Jlc3NnYXRld2F5LmlzdGlvLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbA==
  CATEGORY_URL: aHR0cDovL2lzdGlvLWluZ3Jlc3NnYXRld2F5LmlzdGlvLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbA==
  ENTRY_URL: aHR0cDovL2lzdGlvLWluZ3Jlc3NnYXRld2F5LmlzdGlvLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbA==
  PORT: MzAwMA==
  SECRET_KEY: eW91cl9zZWNyZXRfa2V5
kind: Secret
metadata:
  name: task-frontend
  namespace: prod
---
apiVersion: v1
data:
  DATABASE_NAME: eWFnbmVzaA==
  DATABASE_URL: eWFnbmVzaC10aWRiLmRiLnN2Yy5jbHVzdGVyLmxvY2FsOjQwMDA=
  DB_PASSWORD: WU9VUl9QQVNTV09SRF9IRVJF
  DB_USERNAME: cm9vdA==
kind: Secret
metadata:
  name: common-backend
  namespace: prod
