apiVersion: v1
kind: Service
metadata:
  name: task-by-who
  namespace: prod
spec:
  selector:
    app: task-by-who
  type: ClusterIP
  ports:
  - name: task-by-who
    protocol: TCP
    port: 8082
    targetPort: 8082
